ALTER TABLE chat_session
    ADD COLUMN IF NOT EXISTS corps_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS gender VARCHAR(20),
    ADD COLUMN IF NOT EXISTS marital_status VARCHAR(40),
    ADD COLUMN IF NOT EXISTS children_count INTEGER,
    ADD COLUMN IF NOT EXISTS address TEXT;

ALTER TABLE soldier_registration
    ADD COLUMN IF NOT EXISTS corps_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS gender VARCHAR(20),
    ADD COLUMN IF NOT EXISTS marital_status VARCHAR(50),
    ADD COLUMN IF NOT EXISTS number_of_children INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS address TEXT;
